# syntax=docker/dockerfile:1

# hadolint ignore=DL3007
FROM archlinux:latest

RUN \
    --mount=type=cache,target=/var/cache/ \
    <<END
    # install packages
    pacman -Syu --noconfirm --needed \
        sudo

    # user configuration
    useradd -m user
    echo "user ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/user
END

USER user
