# syntax=docker/dockerfile:1

FROM rockylinux:9

# hadolint ignore=DL3041
RUN \
    --mount=type=cache,target=/var/cache \
    <<END
    set -eux

    # system update & install packages
    dnf -y update
    dnf install -y \
        sudo \
        systemd \
        ;
    dnf clean all

    # user configuration
    useradd -m rocky
    echo "rocky ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/rocky
END

USER rocky
