# syntax=docker/dockerfile:1

# hadolint ignore=DL3007
FROM archlinux:latest

RUN \
    --mount=type=cache,target=/var/cache/ \
    <<END
    set -eux

    # system update & install packages
    pacman -Syu --noconfirm --needed \
        sudo \
        ;

    # user configuration
    useradd -m arch
    echo "arch ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/arch
END

USER arch
