#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source test/lib/common.bash
is_executed && return

find \
    . \
    scripts/ \
    test/ \
    -maxdepth 1 \
    -executable \
    -type f \
    -exec shellcheck -a {} +
