#!/bin/bash

set -eu -o pipefail

REPO_DIR="$(readlink -f "$(dirname "$0")/..")"
readonly REPO_DIR
cd "${REPO_DIR}"

run_test() {
    local -r test_os_name="${1}"
    local -r docker_image_name="dotfiles-test-${test_os_name}"
    local -r dockerfile="test/Dockerfile.${test_os_name}"

    docker build --pull -t "${docker_image_name}" -f "${dockerfile}" .
    docker run --rm -v "${REPO_DIR}:/dotfiles" "${docker_image_name}" /dotfiles/install
}

run_test archlinux
