#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."
source test/lib/test_common.bash
is_executed && return

group_start_file
{
    run_test arch install
}
group_end
