#!/bin/bash

set -eu -o pipefail

REPO_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")"
readonly REPO_DIR
cd "${REPO_DIR}"

find \
    . \
    scripts/ \
    test/ \
    -maxdepth 1 \
    -executable \
    -type f \
    -exec shellcheck {} +
