HISTFILE=~/.zsh/history
HISTSIZE=100000
SAVEHIST=100000
bindkey -e

autoload -Uz compinit
compinit

# autoload predict-on
# predict-on

autoload colors
colors

# source ~/.zprofile

setopt auto_cd appendhistory extendedglob notify
setopt prompt_subst
setopt nobeep
setopt long_list_jobs
setopt list_types
setopt auto_list
setopt auto_menu
setopt auto_param_keys
setopt auto_param_slash
setopt auto_remove_slash
setopt brace_ccl
setopt complete_aliases

setopt hist_ignore_dups
setopt hist_ignore_space
setopt hist_no_store
setopt extended_history
setopt hist_verify

setopt auto_pushd
setopt pushd_ignore_dups
setopt equals
setopt magic_equal_subst
setopt numeric_glob_sort
setopt share_history
setopt correct
setopt noflowcontrol

setopt list_packed
setopt rec_exact

# source ~/.zsh/auto-fu.zsh
# function zle-line-init() {
#   auto-fu-init
# }
# zle -N zle-line-init
# zstyle ':auto-fu:var' postdisplay $''

case $(uname) in
    Darwin)
        eval `gdircolors`
        ;;
    Linux)
        eval `dircolors`
        ;;
esac
export ZLS_COLORS=$LS_COLORS
zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}

zstyle ':completion:*:default' menu select=1
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}'

zstyle ':completion:*' verbose yes
zstyle ':completion:*' completer _oldlist _complete _match _ignored \
    _approximate _list _history
zstyle ':completion:*:descriptions' format \
    "%F{yellow}%B%d%b%f"
zstyle ':completion:*:messages' format \
    "%F{yellow}%d%f"
zstyle ':completion:*:warnings' format \
    "%F{red}No matches for: %F{yellow}%d%f"
zstyle ':completion:*:options' desctiption 'yes'
zstyle ':completion:*' keep-prefix
zstyle ':completion:*' group-name ''

if command -v starship >/dev/null 2>&1; then
    eval $(starship init zsh)
fi
SPROMPT="%{${fg[yellow]}%}correct: %R -> %r [nyae]? %{${reset_color}%}"

# コマンドラインスタックを表示させる
show_buffer_stack() {
  POSTDISPLAY="
stack: $LBUFFER"
  zle push-line-or-edit
}
zle -N show_buffer_stack
bindkey "^q" show_buffer_stack
bindkey "^[q" show_buffer_stack
bindkey "^[Q" show_buffer_stack

limit coredumpsize unlimited
ulimit -c unlimited

[ -f ~/.config/zsh/env.zsh   ] && source ~/.config/zsh/env.zsh
[ -f ~/.config/zsh/alias.zsh ] && source ~/.config/zsh/alias.zsh
[ -f ~/.config/zsh/ssh.zsh   ] && source ~/.config/zsh/ssh.zsh
[ -f ~/.config/zsh/tmux.zsh  ] && source ~/.config/zsh/tmux.zsh
[ -f ~/.config/zsh/fzf.zsh   ] && source ~/.config/zsh/fzf.zsh
[ -f ~/.config/zsh/local.zsh ] && source ~/.config/zsh/local.zsh
