#!/bin/bash

set -eu -o pipefail

REPO_DIR="$(realpath "$(dirname "${BASH_SOURCE[0]}")")"
readonly REPO_DIR
cd "${REPO_DIR}"

source ./scripts/common.bash
is_executed && return

source scripts/prepare.bash

case "${OS_ID}" in
"${OS_ARCH}")
    source scripts/install_paru.bash
    ;;
"${OS_ROCKY_9}")
    source scripts/install_epel.bash
    ;;
esac

source scripts/install_curl.bash

source scripts/install_zsh.bash
source scripts/install_tmux.bash
source scripts/install_git.bash
source scripts/install_tig.bash
source scripts/install_emacs.bash
source scripts/install_vim.bash
source scripts/install_keychain.bash

source scripts/install_rustup.bash
source scripts/install_cargo_binstall.bash
source scripts/install_cargo_update.bash
source scripts/install_topgrade.bash
source scripts/install_rhq.bash
source scripts/install_starship.bash
source scripts/install_bat.bash
source scripts/install_ripgrep.bash
source scripts/install_skim.bash
source scripts/install_delta.bash

source scripts/remove_deprecated.bash

./setup.sh

info "done."
