(require 'gtags)
(add-hook 'gtags-mode-hook (lambda () (setq gtags-select-buffer-single t)))
(progn
  (define-key gtags-mode-map "\C-ch" 'gtags-display-browser)
  (define-key gtags-mode-map "\C-]" 'gtags-find-tag-from-here)
  ;; (define-key gtags-mode-map "\C-t" 'gtags-pop-stack)
  (define-key gtags-mode-map "\C-cP" 'gtags-find-file)
  (define-key gtags-mode-map "\C-cf" 'gtags-parse-file)
  (define-key gtags-mode-map "\C-cg" 'gtags-find-with-grep)
  (define-key gtags-mode-map "\C-cI" 'gtags-find-with-idutils)
  (define-key gtags-mode-map "\C-cs" 'gtags-find-symbol)
  (define-key gtags-mode-map "\C-cr" 'gtags-find-rtag)
  (define-key gtags-mode-map "\C-ct" 'gtags-find-tag)
  (define-key gtags-mode-map "\C-cd" 'gtags-find-tag)
  (define-key gtags-mode-map "\C-cv" 'gtags-visit-rootdir)
                                        ; common
  (define-key gtags-mode-map "\e*" 'gtags-pop-stack)
  (define-key gtags-mode-map "\e." 'gtags-find-tag)
  (define-key gtags-mode-map "\C-x4." 'gtags-find-tag-other-window)
  (if gtags-disable-pushy-mouse-mapping nil
    (define-key gtags-mode-map [mouse-3] 'gtags-pop-stack)
    (define-key gtags-mode-map [mouse-2] 'gtags-find-tag-by-event)))
(progn
  (define-key gtags-select-mode-map "\e*" 'gtags-pop-stack)
  (define-key gtags-select-mode-map "\^?" 'scroll-down)
  (define-key gtags-select-mode-map " " 'scroll-up)
  (define-key gtags-select-mode-map "\C-b" 'scroll-down)
  (define-key gtags-select-mode-map "\C-f" 'scroll-up)
  (define-key gtags-select-mode-map "k" 'previous-line)
  (define-key gtags-select-mode-map "j" 'next-line)
  (define-key gtags-select-mode-map "p" 'previous-line)
  (define-key gtags-select-mode-map "n" 'next-line)
  (define-key gtags-select-mode-map "q" 'gtags-pop-stack)
  (define-key gtags-select-mode-map "u" 'gtags-pop-stack)
  (define-key gtags-select-mode-map "\C-t" 'gtags-pop-stack)
  (define-key gtags-select-mode-map "\C-m" 'gtags-select-tag)
  (define-key gtags-select-mode-map "\C-o" 'gtags-select-tag-other-window)
  (define-key gtags-select-mode-map "\e." 'gtags-select-tag)
  (if gtags-disable-pushy-mouse-mapping nil
    (define-key gtags-select-mode-map [mouse-3] 'gtags-pop-stack)
    (define-key gtags-select-mode-map [mouse-2] 'gtags-select-tag-by-event)))
