(require 'zlc)
(let ((map minibuffer-local-map))
  (define-key map (kbd "C-S-n") 'zlc-select-next-vertical)
  (define-key map (kbd "C-S-p") 'zlc-select-previous-vertical)
  (define-key map (kbd "C-S-f") 'zlc-select-next)
  (define-key map (kbd "C-S-b") 'zlc-select-previous)
  (define-key map (kbd "S-<down>")  'zlc-select-next-vertical)
  (define-key map (kbd "S-<up>")    'zlc-select-previous-vertical)
  (define-key map (kbd "S-<right>") 'zlc-select-next)
  (define-key map (kbd "S-<left>")  'zlc-select-previous))
