(when (require 'typescript nil t)
  (add-to-list 'auto-mode-alist '("\\.ts" . typescript-mode))
  ;; (add-to-list 'ac-modes 'typescript-mode)
  (defun typescript-mode-hook-fn ()
    (subword-mode 1)
    (whitespace-mode 1))
  (add-hook 'typescript-mode-hook 'typescript-mode-hook-fn))
(require 'tss)
(tss-config-default)
