(require 'zlc)
(zlc-mode t)
(define-many-keys minibuffer-local-map
  '(("C-S-n" . zlc-select-next-vertical)
    ("C-S-p" . zlc-select-previous-vertical)
    ("C-S-f" . zlc-select-next)
    ("C-S-b" . zlc-select-previous)
    ("S-<down>"  . zlc-select-next-vertical)
    ("S-<up>"    . zlc-select-previous-vertical)
    ("S-<right>" . zlc-select-next)
    ("S-<left>"  . zlc-select-previous)))
