[alias]
show-default-branch = !git symbolic-ref refs/remotes/origin/HEAD --short | sed 's@^origin/@@'
switch-default-branch = !git switch "$(git show-default-branch)"
fetch-default-branch = "!f() { \
  local db cb; \
  db=\"$(git show-default-branch)\"; \
  cb=\"$(git branch --show-current)\"; \
  if [[ \"${db}\" == \"${cb}\" ]]; then \
    git pull origin \"${cb}\" --ff-only; \
  else \
    git fetch origin \"$(git show-default-branch):$(git show-default-branch)\"; \
  fi; \
}; f"

sd = switch-default-branch
sm = switch-default-branch
fd = fetch-default-branch
fm = fetch-default-branch
