[alias]
show-default-branch = "!f() { \
  local ref; \
  ref=\"$(git symbolic-ref refs/remotes/origin/HEAD --short)\" || return 1; \
  sed 's@^origin/@@' <<< \"${ref}\"; \
}; f"
switch-default-branch = "!f() { \
  local db; \
  db=\"$(git show-default-branch)\" || return 1; \
  git switch \"${db}\"; \
}; f"
pull-default-branch = "!f() { \
  local db cb; \
  db=\"$(git show-default-branch)\" || { echo >&2 \"fatal: failed to get default branch\"; return 1; }; \
  cb=\"$(git branch --show-current)\" || { echo >&2 \"fatal: failed to get current branch\"; return 1; }; \
  if [[ \"${db}\" == \"${cb}\" ]]; then \
    git pull origin \"${cb}\" --ff-only; \
  else \
    git fetch origin \"${db}:${db}\"; \
  fi; \
}; f"
cleanup-merged-branch = "!f() { \
  local db cb; \
  db=\"$(git show-default-branch)\" || { echo >&2 \"fatal: failed to get default branch\"; return 1; }; \
  cb=\"$(git branch --show-current)\" || { echo >&2 \"fatal: failed to get current branch\"; return 1; }; \
  [[ \"${db}\" == \"${cb}\" ]] && { echo >&2 \"Already on default branch\"; return 0; }; \
  git merge-base --is-ancestor \"${cb}\" \"${db}\" || { echo >&2 \"Branch is not merged\"; return 1; }; \
  git switch \"${db}\" || { echo >&2 \"fatal: failed to switch to default branch\"; return 1; }; \
  git branch -d \"${cb}\" || { echo >&2 \"fatal: failed to delete merged branch\"; return 1; }; \
}; f"
tidy = "!git pull-default-branch && git fetch --prune"
retire-branch = "!git tidy && git cleanup-merged-branch"

sd = switch-default-branch
sm = switch-default-branch
pd = pull-default-branch
pm = pull-default-branch
fp = fetch --prune
bd = branch -d
cmb = cleanup-merged-branch
rb = retire-branch
