# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

[plugins]

[plugins.tmux-env-autoupdate]
local = '~/.config/zsh/plugins/tmux-env-autoupdate'

[plugins.tmux-ssh-new-window]
local = '~/.config/zsh/plugins/tmux-ssh-new-window'

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'

[plugins.zoxide]
github = 'ajeetdsouza/zoxide'

[plugins.zsh-autocomplete]
github = 'marlonrichert/zsh-autocomplete'
[plugins.zsh-autocomplete.hooks]
post = "source ~/.config/sheldon/hooks/zsh-autocomplete-post.zsh"

[plugins.fzf-history-search]
local = "~/.config/zsh/plugins/fzf-history-search"
