#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

install_package_by_spec <<END
    arch: topgrade@aur
    ubuntu-22.04: topgrade@cargo
    rocky-9: topgrade@cargo
END

assert_command topgrade
