#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

if [[ "$(pwd)" != "$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")" ]]; then
    cd "$(dirname "${BASH_SOURCE[0]}")/.."
    exec ./scripts/"$(basename "${BASH_SOURCE[0]}")" "$@" # to update BASH_SOURCE, etc.
fi
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    # requires rust toolchain
    source scripts/install_rustup

    install_package_by_spec <<END
        arch: cargo-update
        ubuntu-22.04: cargo-update@cargo
        rocky-9: cargo-update@cargo
END

    assert_command cargo-install-update
}
group_end
