#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

if [[ "$(pwd)" != "$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")" ]]; then
    cd "$(dirname "${BASH_SOURCE[0]}")/.."
    exec ./scripts/"$(basename "${BASH_SOURCE[0]}")" "$@" # to update BASH_SOURCE, etc.
fi
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    assert_eq "${OS_ID}" "${OS_ARCH}"

    if ! command -v paru >/dev/null; then
        pacman_install base-devel git

        ensure_directory_exists ~/.cache/paru/clone
        git clone https://aur.archlinux.org/paru-bin.git ~/.cache/paru/clone/paru-bin

        (cd ~/.cache/paru/clone/paru-bin && makepkg -si --noconfirm)
    fi
}
group_end
