#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

install_package_by_spec <<END
    arch: git-delta
    ubuntu-22.04: git-delta@cargo
    rocky-9: git-delta@cargo
END

assert_command delta

ensure_git_config core.pager delta
ensure_git_config interactive.diffFilter "delta --color-only"
