#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

install_package_by_spec <<END
    arch: emacs
    ubuntu-22.04: emacs
    rocky-9: emacs
END

assert_command emacs

ensure_symlink_to_config_exists .config/emacs

# remove old symlinks
ensure_symlink_to_config_not_exists .emacs.d
