#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

install_package_by_spec <<END
    arch: vim
    ubuntu-22.04: vim
    rocky-9: vim
END

assert_command vim

ensure_symlink_to_config_exists .vim

# remove old symlinks
ensure_symlink_to_config_not_exists .vimrc
