#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

assert_eq "${OS_ID}" "${OS_ARCH}"

if ! command -v paru >/dev/null; then
    pacman_install base-devel git

    ensure_directory_exists ~/.cache/paru/clone
    git clone https://aur.archlinux.org/paru-bin.git ~/.cache/paru/clone/paru-bin

    (cd ~/.cache/paru/clone/paru-bin && makepkg -si --noconfirm)
fi
