#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    install_package_by_spec <<END
        arch: keychain
        ubuntu-22.04: keychain
        rocky-9: keychain@epel
END

    assert_command keychain
}
group_end
