#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

if [[ "$(pwd)" != "$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")" ]]; then
    cd "$(dirname "${BASH_SOURCE[0]}")/.."
    exec ./scripts/"$(basename "${BASH_SOURCE[0]}")" "$@" # to update BASH_SOURCE, etc.
fi
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    assert_eq "${OS_ID}" "${OS_ROCKY_9}"

    dnf_install epel-release
}
group_end
