#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

if [[ "$(pwd)" != "$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")" ]]; then
    cd "$(dirname "${BASH_SOURCE[0]}")/.."
    exec ./scripts/"$(basename "${BASH_SOURCE[0]}")" "$@" # to update BASH_SOURCE, etc.
fi
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    install_package_by_spec <<END
        arch: curl
        ubuntu-22.04: curl ca-certificates
        rocky-9: curl-minimal
END

    assert_command curl
}
group_end
