#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    install_package_by_spec <<END
        arch: ripgrep
        ubuntu-22.04: ripgrep
        rocky-9: ripgrep@epel
END

    assert_command rg
}
group_end
