#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

if [[ "$(pwd)" != "$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")" ]]; then
    cd "$(dirname "${BASH_SOURCE[0]}")/.."
    exec ./scripts/"$(basename "${BASH_SOURCE[0]}")" "$@" # to update BASH_SOURCE, etc.
fi
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    install_package_by_spec <<END
        arch: emacs
        ubuntu-22.04: emacs
        rocky-9: emacs
END

    assert_command emacs

    ensure_symlink_to_config_exists .config/emacs

    # remove old symlinks
    ensure_symlink_to_config_not_exists .emacs.d
}
group_end
