#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

if [[ "$(pwd)" != "$(realpath "$(dirname "${BASH_SOURCE[0]}")/..")" ]]; then
    cd "$(dirname "${BASH_SOURCE[0]}")/.."
    exec ./scripts/"$(basename "${BASH_SOURCE[0]}")" "$@" # to update BASH_SOURCE, etc.
fi
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    install_package_by_spec <<END
        arch: topgrade-bin@aur
        ubuntu-22.04: topgrade@cargo
        rocky-9: topgrade@cargo
END

    assert_command topgrade

    ensure_symlink_to_config_exists .config/topgrade.d/disable_self_update.toml
}
group_end
