#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

install_package_by_spec <<END
    arch: starship
    ubuntu-22.04: starship@cargo
    rocky-9: starship@cargo
END

assert_command starship

ensure_symlink_to_config_exists .config/starship.toml
