#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    case "${OS_ID}" in
    "${OS_ARCH}")
        source scripts/prepare_arch
        ;;
    "${OS_UBUNTU_22_04}")
        source scripts/prepare_ubuntu_22_04
        ;;
    "${OS_ROCKY_9}")
        source scripts/prepare_rocky_9
        ;;
    *)
        abort "${OS_ID} is not supported."
        ;;
    esac
}
group_end
