#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

group_start_file
{
    assert_eq "${OS_ID}" "${OS_UBUNTU_22_04}"

    sudo DEBIAN_FRONTEND=noninteractive apt -qq update
    sudo DEBIAN_FRONTEND=noninteractive apt -qq upgrade -y
}
group_end
