#!/bin/bash
# shellcheck source-path=SCRIPTDIR/..

set -eu -o pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."
source ./lib/common.bash
is_executed && return

parse_args "$@"

group_start_file
{
    assert_eq "${OS_ID}" "${OS_ARCH}"

    sudo pacman -Sqyu --noconfirm
}
group_end
