# syntax=docker/dockerfile:1

# hadolint ignore=DL3007
FROM archlinux:latest

ARG bootstrap=false
ARG dry_run=false
ARG user=arch

SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

RUN \
    --mount=type=cache,target=/var/cache/ \
    <<END
    # system update
    pacman -Syu --noconfirm

    if [ "${bootstrap}" = "true" ]; then
        pacman -S --noconfirm --needed \
            curl \
            tar \
            ;
    fi

    # user configuration
    useradd -m "${user}"

    if [ "${dry_run}" = "true" ]; then
        # remove write access to home directory
        chmod -R a-w "$(getent passwd "${user}" | cut -d: -f6)"
    else
        # sudo configuration
        pacman -S --noconfirm --needed \
            sudo \
            ;
        echo "${user} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/10-${user}
    fi
END

USER "${user}"
SHELL ["/bin/bash", "-c"]
