# syntax=docker/dockerfile:1

FROM rockylinux/rockylinux:9

ARG bootstrap=false
ARG dry_run=false
ARG user=rocky

SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

# hadolint ignore=DL3041
RUN \
    --mount=type=cache,target=/var/cache \
    <<END

    # system update
    dnf clean all
    dnf -y update --refresh

    if [ "${bootstrap}" = "true" ]; then
        dnf install -y \
            curl-minimal \
            tar \
            ;
    fi

    # user configuration
    useradd -m "${user}"
    if [ "${dry_run}" = "true" ]; then
        # remove write access to home directory
        chmod -R a-w "$(getent passwd "${user}" | cut -d: -f6)"
    else
        # sudo configuration
        dnf install -y \
            sudo \
            ;
        echo "${user} ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/10-${user}
    fi

    # cleanup
    dnf clean all
END

USER "${user}"
SHELL ["/bin/bash", "-c"]
