# syntax=docker/dockerfile:1

FROM ubuntu:22.04

ARG bootstrap=false

# hadolint ignore=DL3008
RUN \
    --mount=type=cache,target=/var/lib/apt/lists/* \
    <<END
    set -eux

    # system update & install packages
    export DEBIAN_FRONTEND=noninteractive
    apt-get update
    apt-get upgrade -y
    apt-get install -y --no-install-recommends \
        sudo \
        ;

    if [ "${bootstrap}" = "true" ]; then
        apt-get install -y --no-install-recommends \
            ca-certificates \
            curl \
            tar \
            ;
    fi

    # user configuration
    useradd -m jammy
    echo "jammy ALL=(ALL) NOPASSWD: ALL" > /etc/sudoers.d/jammy
END

USER jammy
