;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-environment
        TeX-font
        backward-sexp
        c-electric-delete-forward
        forward-sexp
        kill-region
        seq-end
        seq-home
        ))

(setq mc/cmds-to-run-once
      '(
        TeX-next-error
        toggle-input-method
        ))
