;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        LaTeX-environment
        TeX-font
        backward-sexp
        forward-sexp
        kill-region
        seq-end
        ))

(setq mc/cmds-to-run-once
      '(
        TeX-next-error
        ))
